# -*- coding: utf-8 -*-
__author__ = 'luisgc11'

INFORME_PARCELAS_NAME = "InformeParcelas"
INFORME_PARCELAS_WINDOW_TITLE = "Informe Parcelas"
INFORME_PARCELAS_SETTINGS_FILE_NAME = "InformeParcelas.ini"
INFORME_PARCELAS_COMBOBOX_NO_SELECT_OPTION = " ... "

INFORME_PARCELAS_VERTICES_WINDOW_TITLE = "Informe Parcelas Coordenadas"
INFORME_PARCELAS_VERTICES_NO_POINT_NUMBER = -1
INFORME_PARCELAS_VERTICES_FIRST_POINT_NUMBER = 1
INFORME_PARCELAS_VERTICES_POINT_NUMBER_INCREMENT = 1
INFORME_PARCELAS_VERTICES_POINT_NUMBER_MINIMUM_VALUE = 1
INFORME_PARCELAS_VERTICES_POINT_NUMBER_MAXIMUM_VALUE = 100000

INFORME_PARCELAS_VERTICES_EASTING_PRECISION = "{:.4f}"
INFORME_PARCELAS_VERTICES_NORTHING_PRECISION = "{:.4f}"

INFORME_PARCELAS_EPSG_CODE_GPS = 4326

INFORME_PARCELAS_QML_TEMPLATES_FOLDER = "templates"
INFORME_PARCELAS_QML_TEMPLATES_FOLDER_QML_POINT_NAME_Z = "Point_Name_Z.qml"
INFORME_PARCELAS_QML_TEMPLATES_FOLDER_QML_POINT_NUMBER_Z = "Point_Number_Z.qml"
INFORME_PARCELAS_QML_TEMPLATES_FOLDER_QML_POINT_Z = "Point_Z.qml"
